version: "3.7"

services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 20
    volumes:
      - ./.data/redis:/data

  backend: &backend
    image: delivery-backend:latest
    build:
      context: backend
    ports:
      - 8000:8000
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.data/static:/static
      - ./.data/media:/media
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy

